### ISSUE TITLE
It didn't work in the latest kakoune

### ISSUE THREAD

**Issue by theowenyoung** [occivink/kakoune-buffer-switcher#2]
Hi, Thanks for the great plugin!

I tried it in the latest kakoune, it seems not work, when I press <ret> in the *scratch* file:

```bash
Error: 1:2: 'buffer-switcher-switch': 3:5: 'buffer-switcher-sort-buffers': 2:5: 'eval': 3:9: 'arrange-buffers': no such buffer '
```

**Comment by occivink** [comment]
Yes, that's because of the latest breaking changes. It's a bit tricky, if I make the necessary changes then it won't work with the latest kakoune release anymore. Let me see if I can somehow support both

**Comment by theowenyoung** [comment]
@occivink Thanks, I really like managing buffers like this, so I forked your project, and now it can work well, I also added some new features.

https://github.com/theowenyoung/kakoune-buffer-manager/

**Comment by occivink** [comment]
Nice, it looks like a well-made plugin. 

I've addressed the issue by just breaking backwards compatibility, and adding a warning to the README
